[INPUT]
    name             tail
    tag              logs.tail
    path             /var/lib/docker/containers/**/*.log
    path_key         path
    multiline.parser docker, cri
    parser           docker
    docker_mode      On

[INPUT]
    name     syslog
    tag      logs.syslog
    listen   0.0.0.0
    port     5140
    parser   syslog-rfc3164
    mode     tcp

[INPUT]
    name            fluentbit_metrics
    tag             metrics.internal
    scrape_interval 2

[SERVICE]
    flush        1
    parsers_file parsers.conf

[OUTPUT]
    name  prometheus_remote_write
    match metrics.*
    host  victoriametrics
    port  8428
    uri   /api/v1/write

[OUTPUT]
    name         splunk
    match        logs.*
    host         vlagent
    port         9429
    compress     gzip
    splunk_token test
