[INPUT]
    name             tail
    tag              logs.tail
    path             /var/lib/docker/containers/**/*.log
    path_key         path
    multiline.parser docker, cri
    parser           docker
    docker_mode      On

[INPUT]
    name     syslog
    tag      logs.syslog
    listen   0.0.0.0
    port     5140
    parser   syslog-rfc3164
    mode     tcp

[SERVICE]
    flush        1
    parsers_file parsers.conf

[OUTPUT]
    name           datadog
    match          logs.*
    host           vmauth
    port           8427
    tls            off
    compress       gzip
    apikey         test
    dd_service     test
    dd_source      data
    dd_message_key log
    dd_tags        env:dev
